### ISSUE TITLE
hippylib 3.1.0 doesn't work with Fenics 2019.1.0

### ISSUE THREAD

**Issue by arielxinsu** [hippylib/hippylib#72] opened 2024-07-03 20:28 UTC
Hi, hippylib team

I tried to import hippylib with Fenics 2019.1.0. I got the error message like this:
`---> 1 from hippylib import *

~/.local/lib/python3.6/site-packages/hippylib/__init__.py in <module>
     36 
     37 # utils
---> 38 from .utils import *
     39 
     40 # hIPPYlib model

~/.local/lib/python3.6/site-packages/hippylib/utils/__init__.py in <module>
     18 from .experimental import experimental
     19 from .vector2function import vector2Function
---> 20 from .cartesian2mesh import numpy2MeshFunction, NumpyScalarExpression3D, NumpyScalarExpression2D, NumpyScalarExpression1D
     21 from .random import Random, parRandom
     22 from .parameterList import ParameterList

~/.local/lib/python3.6/site-packages/hippylib/utils/cartesian2mesh.py in <module>
     15 
     16 include_dirs = [".", source_directory]
---> 17 cpp_module = dl.compile_cpp_code(cpp_code, include_dirs=include_dirs)
     18 
     19 numpy2MeshFunction = cpp_module.numpy2MeshFunction

/usr/local/lib/python3.6/dist-packages/dolfin/jit/pybind11jit.py in compile_cpp_code(cpp_code, **kwargs)
     94 
     95     module, signature = dijitso_jit(cpp_code, module_name, params,
---> 96                                     generate=jit_generate)
     97 
     98     return module

/usr/local/lib/python3.6/dist-packages/dolfin/jit/jit.py in mpi_jit(*args, **kwargs)
     45         # Just call JIT compiler when running in serial
     46         if MPI.size(mpi_comm) == 1:
---> 47             return local_jit(*args, **kwargs)
     48 
     49         # Default status (0 == ok, 1 == fail)

/usr/local/lib/python3.6/dist-packages/dolfin/jit/jit.py in dijitso_jit(*args, **kwargs)
    101 @mpi_jit_decorator
    102 def dijitso_jit(*args, **kwargs):
--> 103     return dijitso.jit(*args, **kwargs)
    104 
    105 

/usr/local/lib/python3.6/dist-packages/dijitso/jit.py in jit(jitable, name, params, generate, send, receive, wait)
    151     signature = name
    152     cache_params = params["cache"]
--> 153     lib = lookup_lib(signature, cache_params)
    154     err_info = None
    155 

/usr/local/lib/python3.6/dist-packages/dijitso/cache.py in lookup_lib(lib_signature, cache_params)
    389     if lib is None:
    390         # Cache miss in memory, try looking on disk
--> 391         lib = load_library(lib_signature, cache_params)
    392     else:
    393         debug("Fetched %s from memory cache" % (lib_signature,))

/usr/local/lib/python3.6/dist-packages/dijitso/cache.py in load_library(signature, cache_params)
    361         sys.path.append(os.path.dirname(lib_filename))
    362         # Will raise an exception if it does not load correctly
--> 363         lib = __import__(signature)
    364         debug("Loaded %s from %s" % (signature, lib_filename))
    365     else:

ImportError: generic_type: type "NumpyScalarExpression3D" referenced unknown base type "dolfin::Expression"`

I double checked the dolfin version. It is 2019.1.0 as stated on hippylib website. Am I using a wrong version of Fenics?

**Comment by uvilla** [comment] 2024-07-03 23:59
Hi @arielxinsu ,

thank you for reporting this issue. hIPPYlib does support FEniCS 2019.1; it is actually the only version we test against.

I would recommend the following:

1. Try switching to the development version of hIPPYlib, which is very stable and backward compatible with the latest release.
2. Provide more details on your FEniCS build. Are you installing from source, or conda, or using Docker?

We recently tested a modern Docker image for old FEniCS that uses the main branch of dolfin (which includes support for mixed dimensions problems). It works well, but with a small hack
( https://github.com/hippylib/hippylib/blob/6576baf5852fe0a5dfebb11913515498bd116273/.github/workflows/ci.yaml#L23)

see our CI for more details: https://github.com/hippylib/hippylib/blob/6576baf5852fe0a5dfebb11913515498bd116273/.github/workflows/ci.yaml#L17

please let us know if this Docker image works for you.

**Comment by arielxinsu** [comment] 2024-07-04 01:34
Dear Prof. Umberto Villa

Firstly, I want to thank your team for developing such an great package for inverse problem.

I currently using docker image fenicsproject/stable
docker run --name notebook -w /home/fenics -v $(pwd):/home/fenics/shared -d -p 127.0.0.1:8888:8888 quay.io/fenicsproject/stable 'jupyter-notebook --ip=0.0.0.0'
Best regards,
Xin

**Comment by uvilla** [comment] 2024-07-05 16:42
Dear @arielxinsu ,

The issue is with the docker image you are using. Please use:

```
docker run --name notebook -w /home/fenics -v $(pwd):/home/fenics/shared -d -p 127.0.0.1:8888:8888 quay.io/fenicsproject/stable:2019.1.0.r3 'jupyter-notebook --ip=0.0.0.0'
```

Note the tag `2019.1.0.r3` rather than `latest`

**Comment by arielxinsu** [comment] 2024-07-08 19:42
Thank you so much for the reply. The docker image stable:2019.1.0.r3  works pretty well with hippylib.

**Comment by uvilla** [comment] 2024-07-08 20:18
Glad to hear it is working.

I am going to close this issue, but feel free to reach out again if you encounter any issue :)

**Closed by uvilla** 2024-07-08 20:18 UTC
